### ISSUE TITLE
[Epic] Minimum viable product

### ISSUE THREAD

**Issue by cobraz** [getbranches/todoist-github-bot#3]
### Goal

Build the foundation for a responsive integration between Github and Todoist. This repository was initiated as a response to wanting to improve my workflow, as outlined in cobraz/todoist-action#216. Having integrated Todoist and GitHub based on GitHub Actions (synchronizing every five minutes), I've learned a few things – and recruited a few people to use it as well (like @HanBrustad and @braaar for some).

To create some deliverables based on this epic, I propose our goal, for now, is to create a way that **only issues** are synchronized and that we manually connect the app with GitHub organizations and users (no onboarding). IMHO, this will create a clear value for me, whereas I can disconnect the synchronization I run every five minutes for issues (and keep pull requests).

#### Design and specification 📔

- [ ] Design
- [ ] Docs plan
- [x] Identify preview customers (@cobraz, @HanBrustad and @braaar)
- [ ] Identify QA checks

#### Engineering ⚙️

- [x] Set up a Sinatra app

#### Release planning

- [ ] Demo the feature internally
- [ ] Marketing
  - [ ] Blog post
  - [ ] Social Media
  - [ ] Community _Forums_
  - [ ] Newsletter
- [ ] Communication
  - [ ] Migrations
  - [ ] Support
  - [ ] Depreciation Plan
- [ ] Ship it 🚀
